landing for the first review
lev-stas/camera_repair_scss pull request #1
Opened 2022-03-30 07:56 UTC by lev-stas

2022-04-01 13:19 UTC, vgschevchenko requested changes
Хорошая работа, но еще осталось над чем потрудиться.
Вы молодец, отлично постарались и хорошо применили технологию  флекса и грида.
Работа оставила приятное впечатление. 

## Критерии

1. Соответствие макету
    - [x] <!--10.0--> 1.1 Все элементы из макета сверстаны
    - [ ] <!--4.0--> 1.2 Шрифты, размер, цвет и начертания текста соответствуют макету
	**Комментарий: 	Размер шрифта https://skr.sh/sDFkqvRlXZo **
    - [ ] <!--4.0--> 1.3 Ширина элементов и отступы отличаются от макета не более, чем на `30px` на десктопной версии и на `10px` на остальных размерах экрана, для которых подготовлен макет. Отличия в размерах не должны визуально противоречить макету и выбиваться из заложенной в макет сетки, в этом случае требуется более строгое соответствие размерам макета
	**Комментарий: Размеры элементов сравните с брифом. https://skr.sh/sDF8VkQ4Lop **
	**Комментарий: Размер кнопки. https://skr.sh/sDFZjGB7G7L Размер кнопки в футере. https://skr.sh/sDFzFoVDojC **
	**Комментарий: Размер кнопки на мообильных https://skr.sh/sDFDsOzI9qx **
	**Комментарий: Отступ между элементами https://skr.sh/sDFZAZ3COZv **
	**Комментарий: Размер отступа между элементами https://skr.sh/sDFPaIdI3n7 **
	
    - [x] <!--2.0--> 1.4 Все блоки соответствуют макету в последних версиях Firefox, Google Chrome или Yandex Browser
2. Адаптив
    - [ ] <!--4.0--> 2.1 Отсутствует горизонтальный скролл на всех размерах экрана 320px и более
	**Комментарий: На мобильных у всей страницы появляется горизонтальный скролл. https://skr.sh/sDFk9L2c89w **
    - [x] <!--1.0--> 2.2 Установленная максимальная ширина контента соответствует макету
    - [ ] <!--4.0--> 2.3 Верстка не ломается между брейкпоинтами
    - [x] <!--1.0--> 2.4 Брейкпоинты сгруппированы. Если два брейкпоинта имеют небольшую пиксельную разницу в медиа-правиле они объединены в один
    - [x] <!--4.0--> 2.5 Текст не выпадает из блоков на всех размерах экрана 320px и более 
    - [x] <!--3.0--> 2.6 Изображения не искажаются и выглядят как в макете на всех размерах экрана
    - [x] <!--1.0--> 2.7 Одинаковые свойства в разных медиа-правилах не дублируются
3. Верстка
    - [x] <!--4.0--> 3.1 Нет ошибок валидации [https://validator.w3.org/nu/](https://validator.w3.org/nu/) (Erorrs)
    - [ ] <!--3.0--> 3.2 Используются `<main>`, `<section>`, `<header>`, `<footer>`, `<ul>`, `<nav>`, `<h1-h6>` и `<p>` там, где это необходимо
    - [x] <!--2.0--> 3.3 Не используются элементы `<b>`, `<br>`, `<i>`
    - [x] <!--1.0--> 3.4 Отсутствуют лишние `div` обертки 
    - [x] <!--3.0--> 3.5 Контентные картинки вставлены через `<img>`, и в них присутствует `alt` с описанием, которое соответствует языку страницы
    - [x] <!--2.0--> 3.6 На странице есть заголовок первого уровня
    - [x] <!--2.0--> 3.7 Заголовки соответствуют иерархии страницы
    - [x] <!--1.0--> 3.8 Корректно задан `viewport`, прописаны `title` и `lang`.
4.  CSS
    - [x] <!--2.0--> 4.1 Не используется `!important`
    - [x] <!--2.0--> 4.2 Абсолютное позиционирование не используется без непосредственной необходимости
    - [x] <!--4.0--> 4.3 Использование `height` и `max-height` не приводит к выпадению текста или блоков при переполнении
    - [ ] <!--2.0--> 4.4 Любой интерактивный элемент имеет состояние наведения, состояние наведения берется из макета или используется прозрачность
    - [x] <!--1.0--> 4.5 Для каждого шрифта указаны альтернативные варианты из системных шрифтов и тип шрифта
5. Применение БЭМ
    - [x] <!--4.0--> 5.1 Нет нарушения методологии БЭМ: нет элементов без родительского блока, нет элементов элементов, модификаторы не используются без указания того, что они модифицируют
    - [x] <!--2.0--> 5.2 Не используются селекторы по тегу
    - [ ] <!--3.0--> 5.3 Для одинаковых блоков в макете переиспользуется стили одного БЭМ-блока
    - [ ] <!--1.0--> 5.4 Числа в названиях классов не используются, за исключением классов для элементов, указанных в руководстве по стилю (Style Guide)
    - [x] <!--1.0--> 5.5 Модификатор не отражает позицию элемента в разметке (`paragraph_first`)
    - [x] <!--1.0--> 5.6 Модификаторы не содержат дубли стилей модифицируемого элемента или блока, только изменяющиеся свойства
    - [ ] <!--2.0--> 5.7 Файловая структура построена по БЭМ Nested или БЭМ Flat
- [x] <!--10.0--> 6. Функциональность на JS работает корректно (слайдеры, бургерное меню или другие требования согласно заданию на проект)
7. Структура проекта и оформление кода
    - [ ] <!--2.0--> 7.1 Соблюдена единообразная файловая структура проекта, например, изображения в папке images, шрифты в папке fonts, стили в папке blocks, скрипты в папке scripts, а не разбросаны в разных папках и не хранятся в корне проекта
    - [x] <!--1.0--> 7.2 Код в проекте отформатирован единообразно
    - [x] <!--1.0--> 7.3 Нет нарушений иерархии отступов в разметке, стилях и файлах скриптов
8. Использование SCSS
	- [x] <!--2.0--> 8.1 Файлы стилей имеют расширение SCSS, подключаемый к странице CSS файл получен генерацией из SCSS файлов 
	- [x] <!--2.0--> 8.2 Повторяющеся значения вынесены в переменные, например, используемые цвета, шрифты, размеры экрана для медиазапросов
	- [x] <!--1.0--> 8.3 Корректно используются миксины, миксины не состоят из одного CSS свойства

## Доп. комментарии:
	
	- Проверьте адаптив вплоть до мобильных. 
	- Сверьтесь с макетами по каждому из разрешений. 

## Количество баллов: 71

##Хорошая работа, но еще осталось над чем потрудиться.
Вы молодец, отлично постарались и хорошо применили технологию  флекса и грида.
Работа оставила приятное впечатление. 

## Критерии

1. Соответствие макету
    - [x] <!--10.0--> 1.1 Все элементы из макета сверстаны
    - [ ] <!--4.0--> 1.2 Шрифты, размер, цвет и начертания текста соответствуют макету
	**Комментарий: 	Размер шрифта https://skr.sh/sDFkqvRlXZo **
    - [ ] <!--4.0--> 1.3 Ширина элементов и отступы отличаются от макета не более, чем на `30px` на десктопной версии и на `10px` на остальных размерах экрана, для которых подготовлен макет. Отличия в размерах не должны визуально противоречить макету и выбиваться из заложенной в макет сетки, в этом случае требуется более строгое соответствие размерам макета
	**Комментарий: Размеры элементов сравните с брифом. https://skr.sh/sDF8VkQ4Lop**
	**Комментарий: Размер кнопки. https://skr.sh/sDFZjGB7G7L Размер кнопки в футере. https://skr.sh/sDFzFoVDojC **
	**Комментарий: Размер кнопки на мообильных https://skr.sh/sDFDsOzI9qx **
	**Комментарий: Отступ между элементами https://skr.sh/sDFZAZ3COZv **
	**Комментарий: Размер отступа между элементами https://skr.sh/sDFPaIdI3n7 **
	
    - [x] <!--2.0--> 1.4 Все блоки соответствуют макету в последних версиях Firefox, Google Chrome или Yandex Browser
2. Адаптив
    - [ ] <!--4.0--> 2.1 Отсутствует горизонтальный скролл на всех размерах экрана 320px и более
	**Комментарий: На мобильных у всей страницы появляется горизонтальный скролл. https://skr.sh/sDFk9L2c89w **
    - [x] <!--1.0--> 2.2 Установленная максимальная ширина контента соответствует макету
    - [ ] <!--4.0--> 2.3 Верстка не ломается между брейкпоинтами
    - [x] <!--1.0--> 2.4 Брейкпоинты сгруппированы. Если два брейкпоинта имеют небольшую пиксельную разницу в медиа-правиле они объединены в один
    - [x] <!--4.0--> 2.5 Текст не выпадает из блоков на всех размерах экрана 320px и более 
    - [x] <!--3.0--> 2.6 Изображения не искажаются и выглядят как в макете на всех размерах экрана
    - [x] <!--1.0--> 2.7 Одинаковые свойства в разных медиа-правилах не дублируются
3. Верстка
    - [x] <!--4.0--> 3.1 Нет ошибок валидации [https://validator.w3.org/nu/](https://validator.w3.org/nu/) (Erorrs)
    - [ ] <!--3.0--> 3.2 Используются `<main>`, `<section>`, `<header>`, `<footer>`, `<ul>`, `<nav>`, `<h1-h6>` и `<p>` там, где это необходимо
    - [x] <!--2.0--> 3.3 Не используются элементы `<b>`, `<br>`, `<i>`
    - [x] <!--1.0--> 3.4 Отсутствуют лишние `div` обертки 
    - [x] <!--3.0--> 3.5 Контентные картинки вставлены через `<img>`, и в них присутствует `alt` с описанием, которое соответствует языку страницы
  [...]

2022-04-01 13:19 UTC, vgschevchenko commented on index.html
> +                <div class="warranty-card">
Можете использовать семантический тег `article` для выделения контентно-текстовых блоков.
Особенно если этот блок будет в дальнейшем, где-то еще использоваться не один раз. 
Данный тег отлично подходит, чтобы выделить статью и т.д.
https://developer.mozilla.org/ru/docs/Web/HTML/Element/article

2022-04-01 13:19 UTC, vgschevchenko commented on index.html
> +            <div class="company-banner"> мы открылись </div>
Нужно использовать параграф - тег `div` не имеет семантического значения.

2022-04-01 13:19 UTC, vgschevchenko commented on index.html
> +        <div class="company-banner"> мы открылись </div>
Нужно использовать параграф - тег `div` не имеет семантического значения.

2022-04-01 13:19 UTC, vgschevchenko commented on styles/index.scss
> +
Файловая структура не построена по БЭМ Nested или БЭМ Flat
Сейчас у вас все стили в одном файле.

2022-04-01 13:19 UTC, vgschevchenko commented on styles/index.scss
> +.email-form__button {
Любой интерактивный элемент имеет состояние наведения, состояние наведения берется из макета или используется прозрачность  https://skr.sh/sDFSOsiVgkR

2022-04-01 13:19 UTC, vgschevchenko commented on styles/index.scss
> +.donate__button {
Любой интерактивный элемент имеет состояние наведения, состояние наведения берется из макета или используется прозрачность

2022-04-01 13:19 UTC, vgschevchenko commented on styles/index.scss
> +;
У кнопки в форме и у кнопки в блоке `donate` присутсвуют общие стили. 
Нужно сделать один общий класс, а индивидуальные стили менять при помощи модификатора.

2022-04-01 13:19 UTC, vgschevchenko commented on styles/index.scss
> +@mixin reset {
Для подобный вещей создайте одтедльную директория и сложите туда все миксимы и вспомогательные функции.

2022-04-01 13:19 UTC, vgschevchenko commented on index.html
> +
Добавьте в файл README

* ссылку на GitHub Pages.

2022-04-03 20:10 UTC, lev-stas commented on index.html
> +            <fieldset class="email-form__application">
fixed by removing input field padding

2022-04-04 10:00 UTC, merged